--Crear la base de datos llamada Nomina y ejecutar el siguiente script

USE [Nomina]
GO
/****** Object:  Table [dbo].[log_consulta_nom_nomina_definitiva]    Script Date: 28/04/2022 4:56:43 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[log_consulta_nom_nomina_definitiva](
	[ID_REGISTRO] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO] [nvarchar](30) NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[OPERACION] [nvarchar](10) NOT NULL,
	[DESCRIPCION_DE_EVENTO] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOM_CONCEPTOS_NOMINA]    Script Date: 28/04/2022 4:56:43 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOM_CONCEPTOS_NOMINA](
	[ID_CONCEPTO] [int] IDENTITY(1,1) NOT NULL,
	[DESC_CONCEPTO] [nvarchar](50) NOT NULL,
	[COD_CONCEPTO] [nchar](10) NOT NULL,
 CONSTRAINT [PK_NOM_CONCEPTOS_NOMINA] PRIMARY KEY CLUSTERED 
(
	[ID_CONCEPTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOM_EMPLEADO]    Script Date: 28/04/2022 4:56:43 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOM_EMPLEADO](
	[ID_EMPLEADOS] [int] NOT NULL,
	[ID_SOLICITUD] [int] NOT NULL,
 CONSTRAINT [PK_NOM_EMPLEADO] PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOM_NOMINA_DEFINITIVA]    Script Date: 28/04/2022 4:56:43 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOM_NOMINA_DEFINITIVA](
	[REGISTRO] [int] IDENTITY(1,1) NOT NULL,
	[FCH_CRE] [datetime] NOT NULL,
	[ID_CONCEPTO] [int] NOT NULL,
	[ID_EMPLEADOS] [int] NOT NULL,
	[VAL_NOMINA] [money] NOT NULL,
	[CANTIDAD] [float] NOT NULL,
 CONSTRAINT [PK_NOM_NOMINA_DEFINITIVA] PRIMARY KEY CLUSTERED 
(
	[REGISTRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_SOLICITUDES_INGRESOS]    Script Date: 28/04/2022 4:56:43 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_SOLICITUDES_INGRESOS](
	[ID_SOLICITUD] [int] IDENTITY(1,1) NOT NULL,
	[DOCUMENTO] [float] NOT NULL,
	[APELLIDOS] [nchar](50) NOT NULL,
	[NOMBRES] [nchar](50) NOT NULL,
 CONSTRAINT [PK_REG_SOLICITUDES_INGRESOS] PRIMARY KEY CLUSTERED 
(
	[ID_SOLICITUD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NOM_EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_NOM_EMPLEADO_REG_SOLICITUDES_INGRESOS1] FOREIGN KEY([ID_SOLICITUD])
REFERENCES [dbo].[REG_SOLICITUDES_INGRESOS] ([ID_SOLICITUD])
GO
ALTER TABLE [dbo].[NOM_EMPLEADO] CHECK CONSTRAINT [FK_NOM_EMPLEADO_REG_SOLICITUDES_INGRESOS1]
GO
ALTER TABLE [dbo].[NOM_NOMINA_DEFINITIVA]  WITH CHECK ADD  CONSTRAINT [FK_NOM_NOMINA_DEFINITIVA_NOM_CONCEPTOS_NOMINA] FOREIGN KEY([ID_CONCEPTO])
REFERENCES [dbo].[NOM_CONCEPTOS_NOMINA] ([ID_CONCEPTO])
GO
ALTER TABLE [dbo].[NOM_NOMINA_DEFINITIVA] CHECK CONSTRAINT [FK_NOM_NOMINA_DEFINITIVA_NOM_CONCEPTOS_NOMINA]
GO
ALTER TABLE [dbo].[NOM_NOMINA_DEFINITIVA]  WITH CHECK ADD  CONSTRAINT [FK_NOM_NOMINA_DEFINITIVA_NOM_EMPLEADO] FOREIGN KEY([ID_EMPLEADOS])
REFERENCES [dbo].[NOM_EMPLEADO] ([ID_EMPLEADOS])
GO
ALTER TABLE [dbo].[NOM_NOMINA_DEFINITIVA] CHECK CONSTRAINT [FK_NOM_NOMINA_DEFINITIVA_NOM_EMPLEADO]
GO
