//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_consulta_nom_nomina_definitiva
    {
        public int ID_REGISTRO { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string OPERACION { get; set; }
        public string DESCRIPCION_DE_EVENTO { get; set; }
    }
}
