//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOM_EMPLEADO()
        {
            this.NOM_NOMINA_DEFINITIVA = new HashSet<NOM_NOMINA_DEFINITIVA>();
        }
    
        public int ID_EMPLEADOS { get; set; }
        public int ID_SOLICITUD { get; set; }
    
        public virtual REG_SOLICITUDES_INGRESOS REG_SOLICITUDES_INGRESOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOM_NOMINA_DEFINITIVA> NOM_NOMINA_DEFINITIVA { get; set; }
    }
}
