//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_SOLICITUDES_INGRESOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REG_SOLICITUDES_INGRESOS()
        {
            this.NOM_EMPLEADO = new HashSet<NOM_EMPLEADO>();
        }
    
        public int ID_SOLICITUD { get; set; }
        public double DOCUMENTO { get; set; }
        public string APELLIDOS { get; set; }
        public string NOMBRES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOM_EMPLEADO> NOM_EMPLEADO { get; set; }
    }
}
